server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: eventity
    static_configs:
      - targets:
          - localhost
        labels:
          job: eventity
          __path__: /var/log/eventity/*.log
